=== cyclopsgroup/cyclopsgroup/trunk/tornado/src/schema/tornado-data.dtd
<!ELEMENT dataset (
    DUser|
    UserObject|
    Group|
    GroupHierarchy|
    UserGroup|
    Acl|
    Role|
    DConf|
    DMenu)*>
<!ATTLIST dataset
    name CDATA #REQUIRED
>

<!ELEMENT DUser EMPTY>
<!ATTLIST DUser
    UserId CDATA #REQUIRED
    UserName CDATA #REQUIRED
    EncryptedPassword CDATA #REQUIRED
    Description CDATA #IMPLIED
    IsSystem CDATA #REQUIRED
    Email CDATA #REQUIRED
    FirstName CDATA #REQUIRED
    MiddleName CDATA #IMPLIED
    LastName CDATA #REQUIRED
    LastSignin CDATA #IMPLIED
    SigninCounter CDATA #REQUIRED
    LastAccess CDATA #IMPLIED
    CreatedTime CDATA #IMPLIED
    IsDisabled CDATA #REQUIRED
>

<!ELEMENT UserObject EMPTY>
<!ATTLIST UserObject
    ObjectId CDATA #REQUIRED
    UserId CDATA #REQUIRED
    ObjectKey CDATA #REQUIRED
    ObjectClassName CDATA #REQUIRED
    ObjectData CDATA #IMPLIED
>

<!ELEMENT Group EMPTY>
<!ATTLIST Group
    GroupId CDATA #REQUIRED
    GroupName CDATA #REQUIRED
    Description CDATA #IMPLIED
    IsSystem CDATA #REQUIRED
    IsDisabled CDATA #REQUIRED
>

<!ELEMENT GroupHierarchy EMPTY>
<!ATTLIST GroupHierarchy
    HierarchyId CDATA #REQUIRED
    GroupId CDATA #REQUIRED
    ParentGroupId CDATA #REQUIRED
>

<!ELEMENT UserGroup EMPTY>
<!ATTLIST UserGroup
    ObjectId CDATA #REQUIRED
    UserId CDATA #REQUIRED
    GroupId CDATA #REQUIRED
>

<!ELEMENT Acl EMPTY>
<!ATTLIST Acl
    AclId CDATA #REQUIRED
    OwnerName CDATA #REQUIRED
    OwnerType CDATA #REQUIRED
    IsRole CDATA #REQUIRED
    Permission CDATA #REQUIRED
>

<!ELEMENT Role EMPTY>
<!ATTLIST Role
    RoleId CDATA #REQUIRED
    RoleName CDATA #REQUIRED
    Description CDATA #IMPLIED
>

<!ELEMENT DConf EMPTY>
<!ATTLIST DConf
    ConfId CDATA #REQUIRED
    ConfKey CDATA #REQUIRED
    ConfValue CDATA #IMPLIED
>

<!ELEMENT DMenu EMPTY>
<!ATTLIST DMenu
    MenuId CDATA #REQUIRED
    ParentId CDATA #REQUIRED
    MenuName CDATA #REQUIRED
    Description CDATA #IMPLIED
    Href CDATA #REQUIRED
>

=== cyclopsgroup/cyclopsgroup/trunk/tornado/src/schema/tornado-data.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no" ?>
<!DOCTYPE dataset SYSTEM "file://tornado-data.dtd">
<dataset name="all">
    <DUser UserId="1" UserName="guest" EncryptedPassword="Z3Vlc3Q=" IsSystem="1" IsDisabled="0" Email="test@cyclops.org" SigninCounter="0" FirstName="John" LastName="Clark"/>
    <DUser UserId="2" UserName="administrator" EncryptedPassword="YWRtaW5pc3RyYXRvcg==" IsSystem="1" IsDisabled="0" Email="test@cyclops.org" SigninCounter="0" FirstName="John" LastName="Clark"/>
    <DUser UserId="21" UserName="jason" EncryptedPassword="amFzb24=" IsSystem="0" IsDisabled="0" Email="test@cyclops.org" SigninCounter="0" FirstName="John" LastName="Clark"/>
    <DUser UserId="22" UserName="john" EncryptedPassword="am9obg==" IsSystem="1" IsDisabled="0" Email="test@cyclops.org" SigninCounter="0" FirstName="John" LastName="Clark"/>
    <DUser UserId="23" UserName="joel" EncryptedPassword="am9lbA==" IsSystem="1" IsDisabled="0" Email="test@cyclops.org" SigninCounter="0" FirstName="John" LastName="Clark"/>
    <Group GroupId="1" GroupName="administrators" IsSystem="1" IsDisabled="0"/>
    <Group GroupId="2" GroupName="users" IsSystem="1" IsDisabled="0"/>
    <UserGroup ObjectId="1" UserId="2" GroupId="1"/>
    <UserGroup ObjectId="2" UserId="22" GroupId="2"/>
    <UserGroup ObjectId="3" UserId="23" GroupId="2"/>
    <Acl AclId="1" OwnerType="U" OwnerName="guest" IsRole="0" Permission="screen:Index.vm"/>
    <Acl AclId="2" OwnerType="U" OwnerName="guest" IsRole="0" Permission="screen:Redirect.vm"/>
    <Acl AclId="3" OwnerType="U" OwnerName="guest" IsRole="0" Permission="screen:pub,*.vm"/>
    <Acl AclId="6" OwnerType="U" OwnerName="guest" IsRole="0" Permission="action:UserIdentify|doSignin"/>
    <Acl AclId="11" OwnerType="G" OwnerName="administrators" IsRole="1" Permission="almighty"/>
    <Acl AclId="12" OwnerType="G" OwnerName="users" IsRole="1" Permission="basic"/>
    <Acl AclId="21" OwnerType="R" OwnerName="almighty" IsRole="0" Permission="screen:*.vm"/>
    <Acl AclId="22" OwnerType="R" OwnerName="almighty" IsRole="0" Permission="action:*|do*"/>
    <Acl AclId="31" OwnerType="R" OwnerName="basic" IsRole="0" Permission="screen:system,Index.vm"/>
    <Acl AclId="32" OwnerType="R" OwnerName="basic" IsRole="0" Permission="screen:system,user,*.vm"/>
    <Acl AclId="36" OwnerType="R" OwnerName="basic" IsRole="0" Permission="action:UserIdentify|*"/>
    <Acl AclId="37" OwnerType="R" OwnerName="basic" IsRole="0" Permission="action:system.user.*|*"/>
    <Acl AclId="38" OwnerType="R" OwnerName="basic" IsRole="0" Permission="action:pub.*|*"/>
    <Role RoleId="1" RoleName="almighty"/>
    <Role RoleId="2" RoleName="basic"/>
    <DConf ConfId="11" ConfKey="services.UserService.user.implementation" ConfValue="com.cyclops.tornado.User"/>
    <DConf ConfId="12" ConfKey="services.UserService.listener" ConfValue="com.cyclops.tornado.modules.PassportBuilder"/>
    <DConf ConfId="13" ConfKey="services.UserService.listener" ConfValue="com.cyclops.tornado.modules.UserSigninCounter"/>
    <DConf ConfId="21" ConfKey="services.NavigatorService.loader" ConfValue="resource"/>
    <DConf ConfId="22" ConfKey="services.NavigatorService.loader.resource.classname" ConfValue="com.cyclops.tornado.services.navigator.ResourceNavigatorLoader"/>
    <DConf ConfId="23" ConfKey="services.NavigatorService.loader.resource.name" ConfValue="portal.xml"/>
    <DConf ConfId="25" ConfKey="services.NavigatorService.loader" ConfValue="db"/>
    <DConf ConfId="26" ConfKey="services.NavigatorService.loader.db.classname" ConfValue="com.cyclops.tornado.services.navigator.DBNavigatorLoader"/>
    <DMenu MenuId="1" MenuName="Sample" ParentId="-1" Href="sample,Index.vm"/>
    <DMenu MenuId="2" MenuName="Sample Home" ParentId="1" Href="sample,Home.vm"/>
    <DMenu MenuId="3" MenuName="Sample Page1" ParentId="2" Href="sample,Page1.vm"/>
    <DMenu MenuId="4" MenuName="Sample Page2" ParentId="1" Href="sample,Page2.vm"/>
</dataset>
